config/routes.rb
Lumawak::Application.routes.draw do

  resources :projects do
    member do
      get 'browse'
      get 'deploy'
      post 'deploy'
    end
  end
  resources :commits
  root :to => 'projects#dashboard'

end

app/models/commit.rb
class Commit < ActiveRecord::Base
  # attr_accessible :title, :body
  belongs_to :project

  attr_accessible :number, :comment, :project_id
end

app/models/project.rb
class Project < ActiveRecord::Base
  has_many :commits, :dependent => :destroy

  attr_accessible :name, :description, :color, :projecttype, :url, :gitpath, :path
  validates :name, :uniqueness => true, :presence => true
  validates :url, :uniqueness => true
  validates :gitpath, :presence => true

  def load_conf
    config = YAML.load_file(Rails.root.join("config","config.yml"))[Rails.env]
    return config
  end

  #returns Git repository object
  def repository options={:init => false}
    unless self.gitpath.blank?
      if (options[:init])
        repository = Git.init(self.path) if File.directory?(self.path)
      else
        path = self.load_conf['git_path'].concat(self.gitpath)
        repository = Git.bare(path) if File.directory?(path)
      end
    end
    return repository
  end

  def logs nb=5, options={:bydate => false, :commits => false}
    gcommits = {}
    unless self.repository.blank?
      repository.log(nb).each do |commit_hash|
        gcommits[commit_hash] = repository.gcommit(commit_hash)
      end
    end
    if options[:bydate]
      gcommits = self.logsByDate(gcommits)
    end
    if options[:commits]
      gcommits = self.logCommits(gcommits, options[:commits])
    end
    return gcommits
  end

  def logsByDate gcommits
    unless gcommits.blank?
      commits = {}
      gcommits.each do |commit|
        date = commit.first.author_date.strftime("%d/%m/%Y")
        if commits[date].blank?
          commits[date] = commit
        else
          commits[date].concat(commit)
        end
      end
      return commits
    end
  end

  def logCommits gcommits, optcommits
    unless gcommits.blank?
      commits = {}
      opt = optcommits.map{|e| e.number}
      hash = 'none'
      gcommits.each do |commit|
        hash = commit.first.to_s if opt.include? commit.first.to_s
        if commits[hash].blank?
          commits[hash] = [commit.first]
        else
          commits[hash].concat([commit.first])
        end
      end
      return commits
    end
  end

  def gtree commit="HEAD^{tree}", options={:subtrees => true, :blobs => true}
    tree = {}
    unless self.repository.blank?
      gtree = self.repository.gtree(commit)
      if options[:blobs]
        tree = {:blobs => gtree.blobs}
      end
      if options[:subtrees]
        tree.merge!({:subtrees => gtree.subtrees})
      end
    end
    return tree
  end

  def deploy hash, remote='origin', comment=''
    repo = self.repository({:init => true})
    if hash.blank? && remote.blank? && repo.blank? && repo.remotes.include?(remote)
      return false
    else
      repo.fetch(remote)
      repo.reset_hard(repo.gcommit(hash))
      self.commits.create(:number => hash, :comment => comment)
      return true
    end
  end
end

app/controllers/application_controller.rb
require 'yaml'

class ApplicationController < ActionController::Base
  protect_from_forgery
  http_basic_authenticate_with :name => "seyb", :password => "naicie0A"
  before_filter :load_conf, :make_menu

  def load_conf
    @config = YAML.load_file(Rails.root.join("config","config.yml"))[Rails.env]
  end

  def make_menu
    @menu = ['dashboard', 'projects', 'commits']
  end
end

app/controllers/commits_controller.rb
class CommitsController < ApplicationController
  def index
    @commits = Commit.all
  end

  def new
    @commit = Commit.new
  end

  def create
    params.inspect
    unless params[:commit].blank?
      @commit = Commit.create(params[:commit])
      if @commit.valid?
        @commit.save
        redirect_to :action => :index
      else
        render :new
      end
    end
  end

  def edit
    @commit = Commit.find(params[:id])
  end

  def update
    @commit = Commit.find(params[:id])
    if !@commit.blank? && @commit.update_attributes(params[:commit])
      redirect_to :action => 'index'
    else
      render :edit
    end
  end

  def destroy
    Commit.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController

  def index
    @projects = Project.all
  end

  def dashboard
    @projects = Project.all
  end

  def new
    @project = Project.new
  end

  def show
    @project = Project.find(params[:id])
    logger.debug @project
  end

  def create
    unless params[:project].blank?
      @project = Project.create(params[:project])
      if @project.valid?
        @project.save
        redirect_to :action => :index
      else
        render :new
      end
    end
  end

  def edit
    @project = Project.find(params[:id])
  end

  def browse
    @project = Project.find(params[:id])
    @hb = (params[:hb].blank?) ? "HEAD" : params[:hb].to_s
    @h = (params[:h].blank?) ? "HEAD" : params[:h].to_s
    @gtree = @project.gtree(@h)
  end

  def deploy
    @project = Project.find(params[:id])
    if !params[:h].blank? && !params[:r].blank? && !@project.blank?
      if @project.deploy(params[:h], params[:r], params[:comment])
        flash[:success] = "Felicitations. Le deploiement a ete un succes !"
        redirect_to :action => :deploy
      else
        flash[:error] = "Desole, le deploiement a echoue"
      end
    end
    @commits = {}
    @branches = @project.repository.branches
    @remotes = @project.repository({:init => true}).remotes
    @project.commits.map{|c| @commits[c.number] = c}
  end

  def update
    @project = Project.find(params[:id])
    if !@project.blank? && @project.update_attributes(params[:project])
      flash[:success] = 'Sauvegarde reussie'
      redirect_to :action => 'show'
    else
       render :edit
    end
  end

  def destroy
    Project.find(params[:id]).destroy
    redirect_to :action => 'index'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/commits_helper.rb
module CommitsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
  def timeago time_date
    a = (Time.now-time_date).to_i
    case a
      when 0 then return "A l\'instant"
      when 1 then return 'Il y a une seconde'
      when 2..59 then return "Il y a #{a.to_s} secondes"
      when 60..119 then return 'Il y a une minute' #120 = 2 minutes
      when 120..3540 then return "Il y a #{(a/60).to_i.to_s} minutes"
      when 3541..7100 then return 'Il y a une heure' # 3600 = 1 hour
      when 7101..82800 then return "Il y a #{((a+99)/3600).to_i.to_s} heures"
      when 82801..172000 then return 'Il y a un jour' # 86400 = 1 day
      when 172001..518400 then return "Il y a #{((a+800)/(60*60*24)).to_i.to_s} jours"
      when 518400..1036800 then return 'Il y a une semaine'
    end
    return "Il y a #{((a+180000)/(60*60*24*7)).to_i.to_s} semaines"
  end

  def gcrumb project, current, search, path={}, init={}
    path = {'HEAD' => current} if path.blank?
    init = {'HEAD' => current} if init.blank?

    unless current == search
      childs = project.gtree(current)[:subtrees]
      if childs.blank?
        path = init
      else
        childs.each do |childname, hash|
          unless path.has_value?(search.to_s)
            path = self.gcrumb(project, hash.to_s, search.to_s, path.merge({childname => hash.to_s}), init)
          end
        end
      end
    end
    return path
  end
end

app/views/commits/_form.html.haml
%dl.form
  =form_for commit, :url => { :action => method } do |f|
    =f.error_messages
    %dt= f.label :number
    %dd= f.text_field :number
    %dt= f.label :comment
    %dd= f.text_area :comment, :size => '39x10'
    %dt= f.label :project_id
    %dd= f.select :project_id, Project.all.collect {|p| [ p.name, p.id ] }
    %dd.submit= f.submit :value => 'Save commit', :name => 'commitment'

app/views/commits/edit.html.haml
%h2 Editer le Commit

=render :partial => 'form', :locals => {:commit => @commit, :method => 'update'}

= link_to 'Retour', commits_path

app/views/commits/index.html.haml
=link_to 'Nouveau commit', new_commit_path, {:class => 'add'}

- if @commits.blank?
  Aucun commit
- else
  %table{:colspan => 0}
    %thead
      %th Number
      %th Commentaire
      %th Actions
    - @commits.each do |commit|
      %tr
        %td= commit.number
        %td= commit.comment
        %td
          = link_to 'Editer', edit_commit_path(commit), :class => 'action pencil'
          = link_to 'Supprimer', commit_path(commit), {:method => 'DELETE', :class => 'action cross'}

app/views/commits/new.html.haml
%h2 Nouveau commit
= @commit.inspect
=render :partial => 'form', :locals => {:commit => @commit, :method => 'create'}

= link_to	'Retour', commits_path

app/views/layouts/application.html.haml
%html
  %head
    %title Lumawak
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags

  %body
    %h1{:class => 'title'}><
      Lumawak
      %span.grey= params[:controller]
    %head
      %ul{:class => 'nav'}
        -@menu.each do |m|
          -if m === 'dashboard'
            %li= link_to_unless_current m.humanize, root_path
          -else
            %li= link_to_if((params[:controller] != m || params[:action] == 'dashboard'), m.humanize, {:controller => m})
    .content
      -if flash[:notice]
        .flash.notice
          %span.icon
          = flash[:notice]
      -if flash[:success]
        .flash.success
          %span.icon
          = flash[:success]
      -if flash[:error]
        .flash.error
          %span.icon
          = flash[:error]
      = yield

app/views/projects/_form.html.haml
%dl.form
  =form_for project, :url => { :action => method } do |f|
    =f.error_messages
    %dt= f.label :name
    %dd= f.text_field :name
    %dt= f.label :description
    %dd= f.text_area :description, :size => '39x10'
    %dt= f.label :url
    %dd= f.url_field :url
    %dt= f.label :gitpath
    %dd= f.text_field :gitpath
    %dt= f.label :path
    %dd= f.text_field :path
    %dt= f.label :color
    %dd= f.select :color, @config['colors']
    %dt= f.label :projecttype
    %dd= f.select :projecttype, {'PHP' => 1, 'RoR' => 2}
    %dd.submit= f.submit

app/views/projects/_heading.html.haml
.heading
  %h2
    %span.color{:style => "background-color:##{@project.color}"}
    = @project.name

  .actions
    = link_to 'Retour à la liste', projects_path, :class => (params[:action]=='index') ? 'list active' : 'list'
    = link_to 'Voir', project_path(@project), :class => (params[:action]=='show') ? 'view active' : 'view'
    = link_to 'Parcourir', browse_project_path(@project), :class => (params[:action]=='browse') ? 'browse active' : 'browse'
    = link_to 'Déploiement', deploy_project_path(@project), :class => (params[:action]=='deploy') ? 'deploy active' : 'deploy'
    = link_to 'Editer', edit_project_path(@project), :class => (params[:action]=='edit') ? 'edit active' : 'edit'

app/views/projects/browse.html.haml
=render :partial => 'heading'


-if @gtree[:subtrees].blank? && @gtree[:blobs].blank?
  Aucune arborescence trouvée

- else
  -breadcrumb = gcrumb(@project, @hb, @h)
  -unless breadcrumb.blank?
    -i = 0
    %ul.breadcrumb
      -breadcrumb.each do |folder, hash|
        %li{:class => (i == 0) ? 'first' : ''}
          =link_to({:action => 'browse', :h => hash.to_s}, {:style => "z-index:#{breadcrumb.count-i}"}) do
            %span
            = h(folder)
        -i = i+1

  .browse
    -unless @gtree[:blobs].blank?
      %ul
        -@gtree[:blobs].each do |fname, blob|
          %li=h fname

    -unless @gtree[:subtrees].blank?
      %ul
        -@gtree[:subtrees].each do |treename, blob|
          %li
            =link_to(h(treename), {:action => 'browse', :h => blob.to_s})
            ="/"

app/views/projects/dashboard.html.haml
=link_to(new_project_path, {:class => 'add button'}) do
  %span Nouveau projet 

- if @projects.blank?
  %p Aucun projet
- else
  - @projects.each do |project|
    %fieldset.project
      %legend
        %span.color{:style => "background-color:##{project.color}"}
        = project.name
      .actions
        = link_to 'Voir', project_path(project), {:class => 'action eye'}
      %dl
        -project.logs.each do |l|
          %dt
            %strong= l.first.to_s.slice(0,8)+' :'
            %span.hash=l.first.author_date.strftime("%d/%m/%Y")
            = ' - '+l.first.author.name+' - '
          %dd=l.first.message

app/views/projects/deploy.html.haml
=render :partial => 'heading'

- if @remotes.count > 1
  %span Remote
  %ul
    - @remotes.each do |remote|
      %li=remote

- if @branches.count > 1
  %span Branches
  %ul
    - @branches.each do |remote|
      %li=remote

-@project.logs(50, {:commits => @project.commits}).each do |key, commits|
  -if key == 'none'
    %fieldset
      %table.projects.deploy
        %thead
          %th.commit Hash
          %th Date
          %th Auteur
          %th{:width => '60%'} Message
          %th.action Action
        -commits.each do |l|
          %tr
            %td
              %strong= l.to_s.slice(0,8)
            %td
              %span.date=l.author_date.strftime("%d/%m/%Y")
            %td.name= l.author.name
            %td.message=l.message
            %td
              .action
                =link_to 'Deploiement', '', {:class => 'action deploy overlay_button', :rel => "#commit_#{l.to_s.slice(0,8)}"}
              .deploy.overlay{:id => "commit_#{l.to_s.slice(0,8)}"}
                .ajax
                  =image_tag 'ajax-loader.gif'
                  %br
                  Deploiement en cours
                .form
                  =form_tag(:action => 'deploy') do
                    = hidden_field_tag :r, @remotes.first
                    = hidden_field_tag :h, l.to_s
                    = label_tag :comment, 'Commentaire'
                    %br
                    %br
                    = text_area_tag :comment, '', :size => '60x10'
                    %br
                    %br
                    = submit_tag 'Lancer le deploiement'

  - else
    %fieldset
      -if @commits.has_key? key
        %legend=h @commits[key].created_at.strftime("%d/%m/%Y") unless @commits[key].number.blank?
        =h @commits[key].comment unless @commits[key].comment.blank?
      %table.projects.deploy
        %thead
          %th.commit Hash
          %th Date
          %th Auteur
          %th{:width => '60%'} Message
        -commits.each do |l|
          %tr
            %td
              %strong= l.to_s.slice(0,8)
            %td
              %span.date=l.author_date.strftime("%d/%m/%Y")
            %td.name= l.author.name
            %td.message=l.message

app/views/projects/edit.html.haml
=render :partial => 'heading'

=render :partial => 'form', :locals => {:project => @project, :method => 'update'}

app/views/projects/index.html.haml
=link_to(new_project_path, {:class => 'add button'}) do
  %span Nouveau projet 

- if @projects.blank?
  %p Aucun projet
- else
  %table.projects
    %thead
      %th.name Nom du projet
      %th.commit Dernier commit
      %th.action{:width => '30%'} Actions
    - @projects.each do |project|
      %tr
        %td.name
          %span.color{:style => "background-color:##{project.color}"}
          = project.name

        -project.logs(1).each do |l|
          %td.date
            %span.date=timeago(l.first.author_date)
        %td.action
          = link_to 'Voir', project_path(project), {:class => 'action eye'}
          = link_to 'Editer', edit_project_path(project), :class => 'action pencil'
          = link_to 'Supprimer', project_path(project), {:method => 'DELETE', :class => 'action cross', :confirm => 'Supprimer ce projet ?'}

app/views/projects/new.html.haml
%h2 Nouveau projet

=render :partial => 'form', :locals => {:project => @project, :method => 'create'}

= link_to	'Retour', projects_path

app/views/projects/show.html.haml
=render :partial => 'heading'

-@project.logs(20, {:bydate => true}).each do |date, glogs|
  %fieldset
    %legend
      =date
    %dl
      -glogs.each_index do |l|
        -if l%2 == 0 
          %dt
            %strong= glogs[l].to_s.slice(0,8)
            =' - '+glogs[l].author.name+' - '
          %dd=glogs[l].message